name: burnout_checkup
channels:
- conda-forge
dependencies:
- python=3.11.14
- pip=26.0.1
- shiny=1.4.0
- pandas=3.0.0
- numpy=2.4.2
- matplotlib=3.10.8
- plotly=6.5.2
- jupyterlab=4.5.4
- ipykernel=7.2.0
- pyarrow=23.0.0
- openpyxl=3.1.5
- scikit-learn=1.8.0
- python-dotenv=1.2.1